//tier1 upgrade frame_________________________________________________
{x: -1, y: 0, z: -1, id: BlockID.m1},
{x: -1, y: 0, z: +1, id: BlockID.m1},
{x: +1, y: 0, z: +1, id: BlockID.m1},
{x: +1, y: 0, z: -1, id: BlockID.m1},

{x: +1, y: -1, z: 0, id: BlockID.m1},
{x: 0, y: -1, z: -1, id: BlockID.m1},
{x: -1, y: -1, z: 0, id: BlockID.m1},
{x: 0, y: -1, z: +1, id: BlockID.m1},

{x: +2, y: -1, z: -2, id: BlockID.m1},
{x: -2, y: -1, z: -2, id: BlockID.m1},
{x: -2, y: -1, z: +2, id: BlockID.m1},
{x: +2, y: -1, z: +2, id: BlockID.m1},

{x: +1, y: -2, z: -2, id: BlockID.m1},
{x: +2, y: -2, z: -1, id: BlockID.m1},
{x: +2, y: -2, z: +1, id: BlockID.m1},
{x: +1, y: -2, z: +2, id: BlockID.m1},
{x: -1, y: -2, z: +2, id: BlockID.m1},
{x: -2, y: -2, z: +1, id: BlockID.m1},
{x: -2, y: -2, z: -1, id: BlockID.m1},
{x: -1, y: -2, z: -2, id: BlockID.m1},


//tier2 upgrade frame_________________________________________________
{x: +3, y: -2, z: -3, id: BlockID.m2},
{x: +3, y: -2, z: +3, id: BlockID.m2},
{x: -3, y: -2, z: +3, id: BlockID.m2},
{x: -3, y: -2, z: -3, id: BlockID.m2},
{x: +2, y: -3, z: -3, id: BlockID.m2},

{x: +3, y: -3, z: -2, id: BlockID.m2},
{x: +3, y: -3, z: +2, id: BlockID.m2},
{x: +2, y: -3, z: +3, id: BlockID.m2},
{x: -2, y: -3, z: +3, id: BlockID.m2},
{x: -3, y: -3, z: +2, id: BlockID.m2},
{x: -3, y: -3, z: -2, id: BlockID.m2},
{x: -2, y: -3, z: -3, id: BlockID.m2},

{x: +3, y: -3, z: 0, id: BlockID.m2},
{x: 0, y: -3, z: -3, id: BlockID.m2},
{x: -3, y: -3, z: 0, id: BlockID.m2},
{x: 0, y: -3, z: +3, id: BlockID.m2},


//tier3 upgrade frame_________________________________________________
{x: +4, y: -3, z: -4, id: BlockID.m3},
{x: +4, y: -3, z: +4, id: BlockID.m3},
{x: -4, y: -3, z: +4, id: BlockID.m3},
{x: -4, y: -3, z: -4, id: BlockID.m3},

{x: +3, y: -4, z: -4, id: BlockID.m3},
{x: +4, y: -4, z: -3, id: BlockID.m3},
{x: +4, y: -4, z: +3, id: BlockID.m3},
{x: +3, y: -4, z: +4, id: BlockID.m3},
{x: -3, y: -4, z: +4, id: BlockID.m3},
{x: -4, y: -4, z: +3, id: BlockID.m3},
{x: -4, y: -4, z: -3, id: BlockID.m3},
{x: -3, y: -4, z: -4, id: BlockID.m3},

{x: +3, y: -4, z: -1, id: BlockID.m3},
{x: +3, y: -4, z: +1, id: BlockID.m3},
{x: +1, y: -4, z: +3, id: BlockID.m3},
{x: -1, y: -4, z: +3, id: BlockID.m3},
{x: -3, y: -4, z: +1, id: BlockID.m3},
{x: -3, y: -4, z: -1, id: BlockID.m3},
{x: -1, y: -4, z: -3, id: BlockID.m3},
{x: +1, y: -4, z: -3, id: BlockID.m3},


//tier4 upgrade frame_________________________________________________
{x: +5, y: -4, z: +5, id: BlockID.m4},
{x: -5, y: -4, z: +5, id: BlockID.m4},
{x: -5, y: -4, z: -5, id: BlockID.m4},
{x: +5, y: -4, z: -5, id: BlockID.m4},

{x: +5, y: -5, z: +4, id: BlockID.m4},
{x: +4, y: -5, z: +5, id: BlockID.m4},
{x: -4, y: -5, z: +5, id: BlockID.m4},
{x: -5, y: -5, z: +4, id: BlockID.m4},
{x: -5, y: -5, z: -4, id: BlockID.m4},
{x: -4, y: -5, z: -5, id: BlockID.m4},
{x: +5, y: -5, z: -4, id: BlockID.m4},
{x: +4, y: -5, z: -5, id: BlockID.m4},

{x: 0, y: -5, z: -3, id: BlockID.m4},
{x: +3, y: -5, z: 0, id: BlockID.m4},
{x: 0, y: -5, z: +3, id: BlockID.m4},
{x: -3, y: -5, z: 0, id: BlockID.m4},
{x: +2, y: -5, z: -4, id: BlockID.m4},
{x: -2, y: -5, z: -4, id: BlockID.m4},
{x: -4, y: -5, z: -2, id: BlockID.m4},
{x: -4, y: -5, z: +2, id: BlockID.m4},
{x: -2, y: -5, z: +4, id: BlockID.m4},
{x: +2, y: -5, z: +4, id: BlockID.m4},
{x: +4, y: -5, z: +2, id: BlockID.m4},
{x: +4, y: -5, z: -2, id: BlockID.m4},

//tier5 upgrade frame_________________________________________________
{x: +6, y: -5, z: +6, id: BlockID.m5},
{x: -6, y: -5, z: +6, id: BlockID.m5},
{x: -6, y: -5, z: -6, id: BlockID.m5},
{x: +6, y: -5, z: -6, id: BlockID.m5},

{x: +6, y: -6, z: +5, id: BlockID.m5},
{x: +5, y: -6, z: +6, id: BlockID.m5},
{x: -5, y: -6, z: +6, id: BlockID.m5},
{x: -6, y: -6, z: +5, id: BlockID.m5},
{x: -6, y: -6, z: -5, id: BlockID.m5},
{x: -5, y: -6, z: -6, id: BlockID.m5},
{x: +5, y: -6, z: -6, id: BlockID.m5},
{x: +6, y: -6, z: -5, id: BlockID.m5},

{x: +4, y: -6, z: -1, id: BlockID.m5},
{x: +4, y: -6, z: +1, id: BlockID.m5},
{x: +1, y: -6, z: +4, id: BlockID.m5},
{x: -1, y: -6, z: +4, id: BlockID.m5},
{x: -4, y: -6, z: +1, id: BlockID.m5},
{x: -4, y: -6, z: -1, id: BlockID.m5},
{x: -1, y: -6, z: -4, id: BlockID.m5},
{x: +1, y: -6, z: -4, id: BlockID.m5},

{x: +5, y: -6, z: -3, id: BlockID.m5},
{x: +5, y: -6, z: +3, id: BlockID.m5},
{x: +3, y: -6, z: +5, id: BlockID.m5},
{x: -3, y: -6, z: +5, id: BlockID.m5},
{x: -5, y: -6, z: +3, id: BlockID.m5},
{x: -5, y: -6, z: -3, id: BlockID.m5},
{x: -3, y: -6, z: -5, id: BlockID.m5},
{x: +3, y: -6, z: -5, id: BlockID.m5},


//tier6 ugrade frame_________________________________________________

{x: +7, y: -6, z: +7, id: BlockID.m6},
{x: -7, y: -6, z: +7, id: BlockID.m6},
{x: -7, y: -6, z: -7, id: BlockID.m6},
{x: +7, y: -6, z: -7, id: BlockID.m6},

{x: +7, y: -7, z: +6, id: BlockID.m6},
{x: +6, y: -7, z: +7, id: BlockID.m6},
{x: -6, y: -7, z: +7, id: BlockID.m6},
{x: -7, y: -7, z: +6, id: BlockID.m6},
{x: -7, y: -7, z: -6, id: BlockID.m6},
{x: -6, y: -7, z: -7, id: BlockID.m6},
{x: +6, y: -7, z: -7, id: BlockID.m6},
{x: +7, y: -7, z: -6, id: BlockID.m6},

{x: +4, y: -7, z: 0, id: BlockID.m6},
{x: 0, y: -7, z: +4, id: BlockID.m6},
{x: -4, y: -7, z: 0, id: BlockID.m6},
{x: 0, y: -7, z: -4, id: BlockID.m6},
{x: -2, y: -7, z: +5, id: BlockID.m6},
{x: +2, y: -7, z: +5, id: BlockID.m6},
{x: +5, y: -7, z: +2, id: BlockID.m6},
{x: +5, y: -7, z: -2, id: BlockID.m6},
{x: -5, y: -7, z: +2, id: BlockID.m6},
{x: -5, y: -7, z: -2, id: BlockID.m6},
{x: -2, y: -7, z: -5, id: BlockID.m6},
{x: +2, y: -7, z: -5, id: BlockID.m6},

{x: +6, y: -7, z: +4, id: BlockID.m6},
{x: +6, y: -7, z: -4, id: BlockID.m6},
{x: +4, y: -7, z: +6, id: BlockID.m6},
{x: +4, y: -7, z: -6, id: BlockID.m6},
{x: -4, y: -7, z: +6, id: BlockID.m6},
{x: -6, y: -7, z: +4, id: BlockID.m6},
{x: -6, y: -7, z: -4, id: BlockID.m6},
{x: -4, y: -7, z: -6, id: BlockID.m6},
