var t6_nb = [
//tier1 upgrade frame_________________________________________________
{x: -1, y: 0, z: -1, id: BlockID.st_f_t6},
{x: -1, y: 0, z: +1, id: BlockID.st_f_t6},
{x: +1, y: 0, z: +1, id: BlockID.st_f_t6},
{x: +1, y: 0, z: -1, id: BlockID.st_f_t6},

{x: +1, y: -1, z: 0, id: BlockID.st_f_t6},
{x: 0, y: -1, z: -1, id: BlockID.st_f_t6},
{x: -1, y: -1, z: 0, id: BlockID.st_f_t6},
{x: 0, y: -1, z: +1, id: BlockID.st_f_t6},

{x: +2, y: -1, z: -2, id: BlockID.st_f_t6},
{x: -2, y: -1, z: -2, id: BlockID.st_f_t6},
{x: -2, y: -1, z: +2, id: BlockID.st_f_t6},
{x: +2, y: -1, z: +2, id: BlockID.st_f_t6},

{x: +1, y: -2, z: -2, id: BlockID.st_f_t6},
{x: +2, y: -2, z: -1, id: BlockID.st_f_t6},
{x: +2, y: -2, z: +1, id: BlockID.st_f_t6},
{x: +1, y: -2, z: +2, id: BlockID.st_f_t6},
{x: -1, y: -2, z: +2, id: BlockID.st_f_t6},
{x: -2, y: -2, z: +1, id: BlockID.st_f_t6},
{x: -2, y: -2, z: -1, id: BlockID.st_f_t6},
{x: -1, y: -2, z: -2, id: BlockID.st_f_t6},

//tier1 structure panel_________________________________________________
{x: +1, y: -2, z: -1, id: BlockID.st_p},
{x: +1, y: -2, z: 0, id: BlockID.st_p},
{x: +1, y: -2, z: +1, id: BlockID.st_p},
{x: 0, y: -2, z: +1, id: BlockID.st_p},
{x: -1, y: -2, z: +1, id: BlockID.st_p},
{x: -1, y: -2, z: 0, id: BlockID.st_p},
{x: -1, y: -2, z: -1, id: BlockID.st_p},
{x: 0, y: -2, z: -1, id: BlockID.st_p},

//tier2 upgrade frame_________________________________________________
{x: +3, y: -2, z: -3, id: BlockID.st_f_t6},
{x: +3, y: -2, z: +3, id: BlockID.st_f_t6},
{x: -3, y: -2, z: +3, id: BlockID.st_f_t6},
{x: -3, y: -2, z: -3, id: BlockID.st_f_t6},
{x: +2, y: -3, z: -3, id: BlockID.st_f_t6},

{x: +3, y: -3, z: -2, id: BlockID.st_f_t6},
{x: +3, y: -3, z: +2, id: BlockID.st_f_t6},
{x: +2, y: -3, z: +3, id: BlockID.st_f_t6},
{x: -2, y: -3, z: +3, id: BlockID.st_f_t6},
{x: -3, y: -3, z: +2, id: BlockID.st_f_t6},
{x: -3, y: -3, z: -2, id: BlockID.st_f_t6},
{x: -2, y: -3, z: -3, id: BlockID.st_f_t6},

{x: +2, y: -3, z: 0, id: BlockID.st_f_t6},
{x: 0, y: -3, z: -2, id: BlockID.st_f_t6},
{x: -2, y: -3, z: 0, id: BlockID.st_f_t6},
{x: 0, y: -3, z: +2, id: BlockID.st_f_t6},

//tier2 structure panel_________________________________________________
{x: +1, y: -3, z: -2, id: BlockID.st_p},
{x: +2, y: -3, z: -2, id: BlockID.st_p},
{x: +2, y: -3, z: -1, id: BlockID.st_p},
{x: +2, y: -3, z: +1, id: BlockID.st_p},
{x: +2, y: -3, z: +2, id: BlockID.st_p},
{x: +1, y: -3, z: +2, id: BlockID.st_p},
{x: -1, y: -3, z: +2, id: BlockID.st_p},
{x: -2, y: -3, z: +2, id: BlockID.st_p},
{x: -2, y: -3, z: +1, id: BlockID.st_p},
{x: -2, y: -3, z: -1, id: BlockID.st_p},
{x: -2, y: -3, z: -2, id: BlockID.st_p},
{x: -1, y: -3, z: -2, id: BlockID.st_p},

//tier3 upgrade frame_________________________________________________
{x: +4, y: -3, z: -4, id: BlockID.st_f_t6},
{x: +4, y: -3, z: +4, id: BlockID.st_f_t6},
{x: -4, y: -3, z: +4, id: BlockID.st_f_t6},
{x: -4, y: -3, z: -4, id: BlockID.st_f_t6},

{x: +3, y: -4, z: -4, id: BlockID.st_f_t6},
{x: +4, y: -4, z: -3, id: BlockID.st_f_t6},
{x: +4, y: -4, z: +3, id: BlockID.st_f_t6},
{x: +3, y: -4, z: +4, id: BlockID.st_f_t6},
{x: -3, y: -4, z: +4, id: BlockID.st_f_t6},
{x: -4, y: -4, z: +3, id: BlockID.st_f_t6},
{x: -4, y: -4, z: -3, id: BlockID.st_f_t6},
{x: -3, y: -4, z: -4, id: BlockID.st_f_t6},

{x: +3, y: -4, z: -1, id: BlockID.st_f_t6},
{x: +3, y: -4, z: +1, id: BlockID.st_f_t6},
{x: +1, y: -4, z: +3, id: BlockID.st_f_t6},
{x: -1, y: -4, z: +3, id: BlockID.st_f_t6},
{x: -3, y: -4, z: +1, id: BlockID.st_f_t6},
{x: -3, y: -4, z: -1, id: BlockID.st_f_t6},
{x: -1, y: -4, z: -3, id: BlockID.st_f_t6},
{x: +1, y: -4, z: -3, id: BlockID.st_f_t6},

//tier3 structure panel_________________________________________________
{x: +2, y: -4, z: 0, id: BlockID.st_p},
{x: 0, y: -4, z: -2, id: BlockID.st_p},
{x: -2, y: -4, z: 0, id: BlockID.st_p},
{x: 0, y: -4, z: +2, id: BlockID.st_p},

{x: +3, y: -4, z: +2, id: BlockID.st_p},
{x: +3, y: -4, z: +3, id: BlockID.st_p},
{x: +2, y: -4, z: +3, id: BlockID.st_p},
{x: -2, y: -4, z: +3, id: BlockID.st_p},
{x: -3, y: -4, z: +3, id: BlockID.st_p},
{x: -3, y: -4, z: +2, id: BlockID.st_p},
{x: -3, y: -4, z: -2, id: BlockID.st_p},
{x: -3, y: -4, z: -3, id: BlockID.st_p},
{x: -2, y: -4, z: -3, id: BlockID.st_p},
{x: +2, y: -4, z: -3, id: BlockID.st_p},
{x: +3, y: -4, z: -3, id: BlockID.st_p},
{x: +3, y: -4, z: -2, id: BlockID.st_p},

//tier3 upgrade frame_________________________________________________
{x: +4, y: -3, z: -4, id: BlockID.st_f_t6},
{x: +4, y: -3, z: +4, id: BlockID.st_f_t6},
{x: -4, y: -3, z: +4, id: BlockID.st_f_t6},
{x: -4, y: -3, z: -4, id: BlockID.st_f_t6},

{x: +3, y: -4, z: -4, id: BlockID.st_f_t6},
{x: +4, y: -4, z: -3, id: BlockID.st_f_t6},
{x: +4, y: -4, z: +3, id: BlockID.st_f_t6},
{x: +3, y: -4, z: +4, id: BlockID.st_f_t6},
{x: -3, y: -4, z: +4, id: BlockID.st_f_t6},
{x: -4, y: -4, z: +3, id: BlockID.st_f_t6},
{x: -4, y: -4, z: -3, id: BlockID.st_f_t6},
{x: -3, y: -4, z: -4, id: BlockID.st_f_t6},

{x: +3, y: -4, z: -1, id: BlockID.st_f_t6},
{x: +3, y: -4, z: +1, id: BlockID.st_f_t6},
{x: +1, y: -4, z: +3, id: BlockID.st_f_t6},
{x: -1, y: -4, z: +3, id: BlockID.st_f_t6},
{x: -3, y: -4, z: +1, id: BlockID.st_f_t6},
{x: -3, y: -4, z: -1, id: BlockID.st_f_t6},
{x: -1, y: -4, z: -3, id: BlockID.st_f_t6},
{x: +1, y: -4, z: -3, id: BlockID.st_f_t6},


//tier4 upgrade frame_________________________________________________
{x: +5, y: -4, z: +5, id: BlockID.st_f_t6},
{x: -5, y: -4, z: +5, id: BlockID.st_f_t6},
{x: -5, y: -4, z: -5, id: BlockID.st_f_t6},
{x: +5, y: -4, z: -5, id: BlockID.st_f_t6},

{x: +5, y: -5, z: +4, id: BlockID.st_f_t6},
{x: +4, y: -5, z: +5, id: BlockID.st_f_t6},
{x: -4, y: -5, z: +5, id: BlockID.st_f_t6},
{x: -5, y: -5, z: +4, id: BlockID.st_f_t6},
{x: -5, y: -5, z: -4, id: BlockID.st_f_t6},
{x: -4, y: -5, z: -5, id: BlockID.st_f_t6},
{x: +5, y: -5, z: -4, id: BlockID.st_f_t6},
{x: +4, y: -5, z: -5, id: BlockID.st_f_t6},

{x: 0, y: -5, z: -3, id: BlockID.st_f_t6},
{x: +3, y: -5, z: 0, id: BlockID.st_f_t6},
{x: 0, y: -5, z: +3, id: BlockID.st_f_t6},
{x: -3, y: -5, z: 0, id: BlockID.st_f_t6},
{x: +2, y: -5, z: -4, id: BlockID.st_f_t6},
{x: -2, y: -5, z: -4, id: BlockID.st_f_t6},
{x: -4, y: -5, z: -2, id: BlockID.st_f_t6},
{x: -4, y: -5, z: +2, id: BlockID.st_f_t6},
{x: -2, y: -5, z: +4, id: BlockID.st_f_t6},
{x: +2, y: -5, z: +4, id: BlockID.st_f_t6},
{x: +4, y: -5, z: +2, id: BlockID.st_f_t6},
{x: +4, y: -5, z: -2, id: BlockID.st_f_t6},

//tier4 structure panel_________________________________________________
{x: -1, y: -5, z: -3, id: BlockID.st_p},
{x: +1, y: -5, z: -3, id: BlockID.st_p},
{x: +3, y: -5, z: -1, id: BlockID.st_p},
{x: +3, y: -5, z: +1, id: BlockID.st_p},
{x: +1, y: -5, z: +3, id: BlockID.st_p},
{x: -1, y: -5, z: +3, id: BlockID.st_p},
{x: -3, y: -5, z: +1, id: BlockID.st_p},
{x: -3, y: -5, z: -1, id: BlockID.st_p},
{x: -4, y: -5, z: +3, id: BlockID.st_p},
{x: -4, y: -5, z: +4, id: BlockID.st_p},
{x: -3, y: -5, z: +4, id: BlockID.st_p},
{x: +3, y: -5, z: +4, id: BlockID.st_p},
{x: +4, y: -5, z: +4, id: BlockID.st_p},
{x: +4, y: -5, z: +3, id: BlockID.st_p},
{x: +4, y: -5, z: -3, id: BlockID.st_p},
{x: +4, y: -5, z: -4, id: BlockID.st_p},
{x: +3, y: -5, z: -4, id: BlockID.st_p},
{x: -4, y: -5, z: -3, id: BlockID.st_p},
{x: -4, y: -5, z: -4, id: BlockID.st_p},
{x: -3, y: -5, z: -4, id: BlockID.st_p},

//tier5 upgrade frame_________________________________________________
{x: +6, y: -5, z: +6, id: BlockID.st_f_t6},
{x: -6, y: -5, z: +6, id: BlockID.st_f_t6},
{x: -6, y: -5, z: -6, id: BlockID.st_f_t6},
{x: +6, y: -5, z: -6, id: BlockID.st_f_t6},

{x: +6, y: -6, z: +5, id: BlockID.st_f_t6},
{x: +5, y: -6, z: +6, id: BlockID.st_f_t6},
{x: -5, y: -6, z: +6, id: BlockID.st_f_t6},
{x: -6, y: -6, z: +5, id: BlockID.st_f_t6},
{x: -6, y: -6, z: -5, id: BlockID.st_f_t6},
{x: -5, y: -6, z: -6, id: BlockID.st_f_t6},
{x: +5, y: -6, z: -6, id: BlockID.st_f_t6},
{x: +6, y: -6, z: -5, id: BlockID.st_f_t6},

{x: +4, y: -6, z: -1, id: BlockID.st_f_t6},
{x: +4, y: -6, z: +1, id: BlockID.st_f_t6},
{x: +1, y: -6, z: +4, id: BlockID.st_f_t6},
{x: -1, y: -6, z: +4, id: BlockID.st_f_t6},
{x: -4, y: -6, z: +1, id: BlockID.st_f_t6},
{x: -4, y: -6, z: -1, id: BlockID.st_f_t6},
{x: -1, y: -6, z: -4, id: BlockID.st_f_t6},
{x: +1, y: -6, z: -4, id: BlockID.st_f_t6},

{x: +5, y: -6, z: -3, id: BlockID.st_f_t6},
{x: +5, y: -6, z: +3, id: BlockID.st_f_t6},
{x: +3, y: -6, z: +5, id: BlockID.st_f_t6},
{x: -3, y: -6, z: +5, id: BlockID.st_f_t6},
{x: -5, y: -6, z: +3, id: BlockID.st_f_t6},
{x: -5, y: -6, z: -3, id: BlockID.st_f_t6},
{x: -3, y: -6, z: -5, id: BlockID.st_f_t6},
{x: +3, y: -6, z: -5, id: BlockID.st_f_t6},

//tier5 structure panel_________________________________________________
{x: +3, y: -6, z: 0, id: BlockID.st_p},
{x: +4, y: -6, z: -2, id: BlockID.st_p},
{x: +4, y: -6, z: +2, id: BlockID.st_p},

{x: 0, y: -6, z: +3, id: BlockID.st_p},
{x: -2, y: -6, z: +4, id: BlockID.st_p},
{x: +2, y: -6, z: +4, id: BlockID.st_p},

{x: -3, y: -6, z: 0, id: BlockID.st_p},
{x: -4, y: -6, z: +2, id: BlockID.st_p},
{x: -4, y: -6, z: -2, id: BlockID.st_p},

{x: 0, y: -6, z: -3, id: BlockID.st_p},
{x: -2, y: -6, z: -4, id: BlockID.st_p},
{x: +2, y: -6, z: -4, id: BlockID.st_p},

{x: +5, y: -6, z: +4, id: BlockID.st_p},
{x: +5, y: -6, z: +5, id: BlockID.st_p},
{x: +4, y: -6, z: +5, id: BlockID.st_p},
{x: -4, y: -6, z: +5, id: BlockID.st_p},
{x: -5, y: -6, z: +5, id: BlockID.st_p},
{x: -5, y: -6, z: +4, id: BlockID.st_p},
{x: -5, y: -6, z: -4, id: BlockID.st_p},
{x: -5, y: -6, z: -5, id: BlockID.st_p},
{x: -4, y: -6, z: -5, id: BlockID.st_p},
{x: +4, y: -6, z: -5, id: BlockID.st_p},
{x: +5, y: -6, z: -5, id: BlockID.st_p},
{x: +5, y: -6, z: -4, id: BlockID.st_p},

//tier6 ugrade frame_________________________________________________
{x: +7, y: -6, z: +7, id: BlockID.st_f_t6},
{x: -7, y: -6, z: +7, id: BlockID.st_f_t6},
{x: -7, y: -6, z: -7, id: BlockID.st_f_t6},
{x: +7, y: -6, z: -7, id: BlockID.st_f_t6},

{x: +7, y: -7, z: +6, id: BlockID.st_f_t6},
{x: +6, y: -7, z: +7, id: BlockID.st_f_t6},
{x: -6, y: -7, z: +7, id: BlockID.st_f_t6},
{x: -7, y: -7, z: +6, id: BlockID.st_f_t6},
{x: -7, y: -7, z: -6, id: BlockID.st_f_t6},
{x: -6, y: -7, z: -7, id: BlockID.st_f_t6},
{x: +6, y: -7, z: -7, id: BlockID.st_f_t6},
{x: +7, y: -7, z: -6, id: BlockID.st_f_t6},

{x: +4, y: -7, z: 0, id: BlockID.st_f_t6},
{x: 0, y: -7, z: +4, id: BlockID.st_f_t6},
{x: -4, y: -7, z: 0, id: BlockID.st_f_t6},
{x: 0, y: -7, z: -4, id: BlockID.st_f_t6},
{x: -2, y: -7, z: +5, id: BlockID.st_f_t6},
{x: +2, y: -7, z: +5, id: BlockID.st_f_t6},
{x: +5, y: -7, z: +2, id: BlockID.st_f_t6},
{x: +5, y: -7, z: -2, id: BlockID.st_f_t6},
{x: -5, y: -7, z: +2, id: BlockID.st_f_t6},
{x: -5, y: -7, z: -2, id: BlockID.st_f_t6},
{x: -2, y: -7, z: -5, id: BlockID.st_f_t6},
{x: +2, y: -7, z: -5, id: BlockID.st_f_t6},

{x: +6, y: -7, z: +4, id: BlockID.st_f_t6},
{x: +6, y: -7, z: -4, id: BlockID.st_f_t6},
{x: +4, y: -7, z: +6, id: BlockID.st_f_t6},
{x: +4, y: -7, z: -6, id: BlockID.st_f_t6},
{x: -4, y: -7, z: +6, id: BlockID.st_f_t6},
{x: -6, y: -7, z: +4, id: BlockID.st_f_t6},
{x: -6, y: -7, z: -4, id: BlockID.st_f_t6},
{x: -4, y: -7, z: -6, id: BlockID.st_f_t6},

//tier6 structure panel_________________________________________________
{x: +4, y: -7, z: 0, id: BlockID.st_f_t6},
{x: +5, y: -7, z: -3, id: BlockID.st_p},
{x: +5, y: -7, z: +3, id: BlockID.st_p},
{x: +6, y: -7, z: +5, id: BlockID.st_p},
{x: +6, y: -7, z: +6, id: BlockID.st_p},
{x: +5, y: -7, z: +6, id: BlockID.st_p},
{x: +6, y: -7, z: -5, id: BlockID.st_p},
{x: +6, y: -7, z: -6, id: BlockID.st_p},
{x: +5, y: -7, z: -6, id: BlockID.st_p},

{x: -4, y: -7, z: 0, id: BlockID.st_f_t6},
{x: -5, y: -7, z: -3, id: BlockID.st_p},
{x: -5, y: -7, z: +3, id: BlockID.st_p},
{x: -6, y: -7, z: +5, id: BlockID.st_p},
{x: -6, y: -7, z: +6, id: BlockID.st_p},
{x: -5, y: -7, z: +6, id: BlockID.st_p},
{x: -6, y: -7, z: -5, id: BlockID.st_p},
{x: -6, y: -7, z: -6, id: BlockID.st_p},
{x: -5, y: -7, z: -6, id: BlockID.st_p},

{x: 0, y: -7, z: -4, id: BlockID.st_f_t6},
{x: -3, y: -7, z: -5, id: BlockID.st_p},
{x: +3, y: -7, z: -5, id: BlockID.st_p},

{x: 0, y: -7, z: +4, id: BlockID.st_f_t6},
{x: -3, y: -7, z: +5, id: BlockID.st_p},
{x: +3, y: -7, z: +5, id: BlockID.st_p},

{x: +4, y: -7, z: -1, id: BlockID.st_p},
{x: +4, y: -7, z: +1, id: BlockID.st_p},
{x: +1, y: -7, z: +4, id: BlockID.st_p},
{x: -1, y: -7, z: +4, id: BlockID.st_p},
{x: -4, y: -7, z: +1, id: BlockID.st_p},
{x: -4, y: -7, z: -1, id: BlockID.st_p},
{x: -1, y: -7, z: -4, id: BlockID.st_p},
{x: +1, y: -7, z: -4, id: BlockID.st_p},

//tier6 modifiers_________________________________________________
{x: +7, y: -7, z: -7, id: BlockID.st_p},
{x: -7, y: -7, z: -7, id: BlockID.st_p},
{x: -7, y: -7, z: +7, id: BlockID.st_p},
{x: +7, y: -7, z: +7, id: BlockID.st_p},
];
var t6_nb_m = [
{x: +1, y: -1, z: -1, id: BlockID.null_modifier},
{x: -1, y: -1, z: -1, id: BlockID.null_modifier},
{x: -1, y: -1, z: +1, id: BlockID.null_modifier},
{x: +1, y: -1, z: +1, id: BlockID.null_modifier},

{x: +2, y: -2, z: -2, id: BlockID.null_modifier},
{x: -2, y: -2, z: -2, id: BlockID.null_modifier},
{x: -2, y: -2, z: +2, id: BlockID.null_modifier},
{x: +2, y: -2, z: +2, id: BlockID.null_modifier},

{x: +3, y: -3, z: -3, id: BlockID.null_modifier},
{x: -3, y: -3, z: -3, id: BlockID.null_modifier},
{x: +3, y: -3, z: +3, id: BlockID.null_modifier},
{x: -3, y: -3, z: +3, id: BlockID.null_modifier},

{x: +4, y: -4, z: -4, id: BlockID.null_modifier},
{x: +4, y: -4, z: +4, id: BlockID.null_modifier},
{x: -4, y: -4, z: +4, id: BlockID.null_modifier},
{x: -4, y: -4, z: -4, id: BlockID.null_modifier},

{x: +5, y: -5, z: +5, id: BlockID.null_modifier},
{x: -5, y: -5, z: +5, id: BlockID.null_modifier},
{x: -5, y: -5, z: -5, id: BlockID.null_modifier},
{x: +5, y: -5, z: -5, id: BlockID.null_modifier},

{x: +6, y: -6, z: +6, id: BlockID.null_modifier},
{x: -6, y: -6, z: +6, id: BlockID.null_modifier},
{x: -6, y: -6, z: -6, id: BlockID.null_modifier},
{x: +6, y: -6, z: -6, id: BlockID.null_modifier},
]